# Generated by Django 2.1.7 on 2019-02-12 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190210_1847'),
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_estimation', models.CharField(choices=[('sh', 'Без оценки'), ('vb', 'Раздражающая статья'), ('bd', 'Совсем неинтересно'), ('hd', 'Неинтересно'), ('av', 'Средне'), ('wl', 'Можно почитать'), ('gd', 'Хорошая статья'), ('vg', 'Очень интересно')], default='sh', max_length=2, verbose_name='Пользовательская оценка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Article', verbose_name='Статья.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='articles',
            field=models.ManyToManyField(through='users.UserArticle', to='sites.Article', verbose_name='Пользовательские сайты'),
        ),
    ]
