# Generated by Django 2.1.7 on 2019-02-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190210_1847'),
        ('users', '0003_auto_20190212_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userarticle',
            unique_together={('article', 'user')},
        ),
    ]
