# Generated by Django 2.1.7 on 2019-02-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190210_1847'),
        ('users', '0004_auto_20190212_2218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersite',
            unique_together={('site', 'user')},
        ),
    ]
