# Generated by Django 2.1.7 on 2019-02-17 19:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True, verbose_name='Адрес')),
                ('has_percents', models.BooleanField(default=False, verbose_name='Проценты в статье.')),
                ('has_prices', models.BooleanField(default=False, verbose_name='Цены.')),
                ('frequent_words', models.CharField(default='', max_length=500, verbose_name='Наиболее частыне слова.')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_portal', models.CharField(blank=True, default='', max_length=20, verbose_name='Краткое название новостного ресурса')),
                ('news_department', models.CharField(blank=True, default='', max_length=10, verbose_name='Краткое имя раздела')),
                ('target_url', models.URLField(verbose_name='Целевой url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный для парсинга сайт')),
            ],
            options={
                'verbose_name': 'Целевой сайт',
                'verbose_name_plural': 'Целевые сайты',
            },
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_estimation', models.CharField(choices=[('sh', 'Без оценки'), ('vb', 'Раздражающая статья'), ('bd', 'Совсем неинтересно'), ('hd', 'Неинтересно'), ('av', 'Средне'), ('wl', 'Можно почитать'), ('gd', 'Хорошая статья'), ('vg', 'Очень интересно')], default='sh', max_length=2, verbose_name='Пользовательская оценка')),
            ],
            options={
                'verbose_name': 'Пользовательская оценка',
                'verbose_name_plural': 'Пользовательские оценки',
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.TextField(blank=True, default='', max_length=500, verbose_name='Ключевое слово для поиска')),
                ('exclude_words', models.TextField(blank=True, default='', max_length=500, verbose_name='Слова для исключающей фильтрации')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Корневой сайт.')),
            ],
            options={
                'verbose_name': 'Инфо ресурс',
                'verbose_name_plural': 'Инфо ресурсы',
            },
        ),
    ]
