# Generated by Django 2.1.5 on 2019-02-02 21:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True, verbose_name='Адрес')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_portal', models.CharField(blank=True, default='', max_length=20, verbose_name='Краткое название новостного ресурса')),
                ('news_department', models.CharField(blank=True, default='', max_length=10, verbose_name='Краткое имя раздела')),
                ('target_url', models.URLField(verbose_name='Целевой url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный для парсинга сайт')),
            ],
            options={
                'verbose_name': 'Целевой сайт',
                'verbose_name_plural': 'Целевые сайты',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['link'], name='sites_artic_link_ae6bd2_idx'),
        ),
    ]
