# Generated by Django 2.1.7 on 2019-02-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Article', verbose_name='Статья.'),
        ),
        migrations.AddField(
            model_name='userarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(through='sites.UserSite', to=settings.AUTH_USER_MODEL, verbose_name='Пользовательские сайты'),
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(through='sites.UserArticle', to=settings.AUTH_USER_MODEL, verbose_name='Пользовательские сайты'),
        ),
        migrations.AlterUniqueTogether(
            name='usersite',
            unique_together={('site', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userarticle',
            unique_together={('article', 'user')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['link'], name='sites_artic_link_ae6bd2_idx'),
        ),
    ]
