# Generated by Django 2.1.5 on 2019-01-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpcontent',
            name='target_site',
            field=models.URLField(verbose_name='Корневой сайт'),
        ),
    ]
