# Generated by Django 2.1.5 on 2019-02-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='frequent_words',
            field=models.CharField(default='', max_length=500, verbose_name='Наиболее частыне слова.'),
        ),
        migrations.AddField(
            model_name='article',
            name='has_percents',
            field=models.BooleanField(default=False, verbose_name='Проценты в статье.'),
        ),
        migrations.AddField(
            model_name='article',
            name='has_prices',
            field=models.BooleanField(default=False, verbose_name='Цены.'),
        ),
    ]
