# Generated by Django 2.1.5 on 2019-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190113_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpcontent',
            name='abstract',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tmpcontent',
            name='body',
            field=models.TextField(default='', verbose_name='Тело статьи'),
        ),
        migrations.AlterField(
            model_name='tmpcontent',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
    ]
