# Generated by Django 2.1.5 on 2019-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20190115_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='key_word',
        ),
        migrations.RemoveField(
            model_name='site',
            name='support_word',
        ),
        migrations.AddField(
            model_name='site',
            name='exclude_words',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Слова для исключающей фильтрации'),
        ),
        migrations.AddField(
            model_name='site',
            name='key_words',
            field=models.TextField(default='', max_length=500, verbose_name='Ключевое слово для поиска'),
        ),
        migrations.AddField(
            model_name='site',
            name='news_department',
            field=models.CharField(default='', max_length=10, verbose_name='Краткое раздела'),
        ),
        migrations.AddField(
            model_name='site',
            name='news_portal',
            field=models.CharField(default='', max_length=10, verbose_name='Краткое название новостного ресурса'),
        ),
    ]
