# Generated by Django 2.1.5 on 2019-01-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20190123_1917'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO sites_site (news_portal, news_department, key_words, target_urls, exclude_words, is_active) VALUES 
            ('tass', 'ekonomika', 'прогноз, достиг, $, инфляц, рублей, сделк, вложит, начислен, млрд, закупил, %, индекс, штраф, итог, слиян, рост, млн, вырос, блок, списан, инвест, экспорт', 'https://tass.ru/ekonomika', '', True);
        """)
    ]
