# Generated by Django 2.1.5 on 2019-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20190128_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TmpContent',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['link'], name='sites_artic_link_ae6bd2_idx'),
        ),
    ]
